### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100

}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100

}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "86ffeb9e8ed841b7b01e1af594cd69b8",
  "accountNumber": "1000000002",
  "amount": 10000

}

### query transaction
GET http://localhost:8080/transaction/9c60a7308dcd4522a5fd1aee2692a754