### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 10000

}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "9b050b77ad624873bbd3062556459ebe",
  "accountNumber": "1000000001",
  "amount": 10000

}